#!/bin/bash

# Git Stash & Pull
gsp() {
  # git checkout $(git branch --all | fzf -q "${1:-}" | tr -d '[:space:]' | sed -e "s/^remotes\/origin\///")
  git add . && git stash && git pull && git stash pop
}
