#!/bin/zsh

n() {
  RESULT=$(jobs | grep -E 'n$|nvim' | tail -1 | sed -E 's/^\[([0-9]+)\].*/\1/')
  if [ ! -z $RESULT ]; then
    fg %$RESULT
  elif [ -f session.vim ]; then
    nvim . -S session.vim
  else
    nvim .
  fi
  return 0
}

