require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
-- require "user.bufferline"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.lualine"
require "user.toggleterm"
require "user.impatient"
require "user.indentline"
require "user.whichkey"
-- require "user.autocommands"
require "user.surround"
require "user.elixir"
require "user.tests"
