require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
-- require "user.comment"
require "user.lualine"
require "user.toggleterm"
-- require "user.indentline"
require "user.whichkey"
require "user.autocommands"
require "user.surround"
require "user.tests"
require "user.lsp"
require "user.gitblame"
require "user.viewpr"
